apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: productpage-ingress
  annotations:
    ianz: triggerbuild
spec:
  rules:
  - host: bookinfo.isv.com
    http:
      paths:
      - path: /
        backend:
          serviceName: productpage
          servicePort: 9080
