apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: productpage-ingress
spec:
  rules:
  - host: bookinfo.tools.azure.nvcodes.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: productpage
            port:
              number: 9080